env: 
    seed:
                799345
    n_levels:
                10  # power level count
    n_t_devices:
                9
    m_r_devices:
                4
    n_bs:
                1   # consant, don't change
    m_usrs:
                4
    R_bs:
            5   # adjust to match n_t_devices
    R_dev:
            1
    r_bs:
            0.01
    r_dev:
            0.001
    sorter:
            power
    metrics:
            - power
            - rate
agent:
    gamma:
            0.0 # discount rate
    learning_rate:
            0.001
    init_epsilon:
            0.9
    min_epsilon:
            0.01
    